### PR TITLE
Remove mimic tags and rename `sim_ignition` to `sim_gazebo`

### PR DESCRIPTION
**Pull request by sea-bass**
I was trying to use this package on Rolling / Ubuntu 24.04 and ran into this problem.

Found it was related to https://github.com/ros-controls/ros2_control/pull/1553, in which the `<mimic>` tags have been deprecated as this information is now looked up directly from URDF.

So these tags, and command interfaces, for mimic joints, should be removed.

---

BTW: This fixes Rolling CI because of a unit test that broke due to the above changes

... though the Coverage build seems to be failing for another reason. Seems to be https://github.com/ros-tooling/action-ros-ci/issues/844

EDIT: fixed in https://github.com/PickNikRobotics/ros2_robotiq_gripper/pull/56

---

I also took the liberty of renaming `sim_ignition` to `sim_gazebo` in accordance to my related PR to the Kortex repo: https://github.com/Kinovarobotics/ros2_kortex/pull/228. But I can concede and pull that out to a future PR.

### CODE REVIEW

**Review by sjahr — DISMISSED** [review]

**Comment by sea-bass** [comment]
It does seem like ros2_control has thrown yet another curveball at us here... I'll take a look later if I can will myself to

**Comment by sjahr** [comment]
Damn, thanks!

**Comment by sea-bass** [comment]
This is the PR that broke things -- fixing now
https://github.com/ros-controls/ros2_control/pull/1585

**Review by sjahr — APPROVED** [review]

**Comment by sjahr** [comment]
Thank you @sea-bass !

**Pull request merged**
